


name: Ci/cd build

on:
  push:
    branches:
      - main

jobs:
  build:
   name : build
   runs-on: [ self-hosted ]
   steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: npm 
        run: npm install
        

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t kartik2311/hello-world:latest .

      - name: Push Docker image
        run: docker push kartik2311/hello-world:latest

      

  deploy: 
    runs-on : [self-hosted]
    steps:
    - name: Deploy to ECS Fargate
      run: |
          terraform init -upgrade

           

          terraform state list
          

          terraform init 

          

          terraform fmt
          
          terraform validate

          

         
          
          terraform destroy -auto-approve

          terraform output
         
          
      working-directory: ./ecs-module
       
        
         









env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: your-region
